<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RobotCommandCenter</AssemblyName>
    <RootNamespace>CommandCenter</RootNamespace>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
